#!/usr/bin/python

import re
import os

FIELDS = "scanfieldspraktisk"

f = open(FIELDS,'r')
fields = f.read()
fields = fields.split("newmode:")
start = fields[1]
topogram = fields[2]
ct = fields[3]
pause = fields[4]
pet = fields[5]

path = "protokoller56/"
path2 = "fprotokoller/"
listing = os.listdir(path)
for file in listing:
    try:

        f = open(path + file,'r')
        proto = f.read()
        proto = proto.split("\n")
    
        newProto = []
        for item in proto:
            item = item.rstrip('\r\n')
            item = item.replace("\t"," ")
            item = re.sub(' +',' ',item)
            newProto.append(item)
    
        proto = newProto
    
    
    
        index = 0
        rindex = -1
        recon = [0,0,0]
        fieldlist = ""
        reconpos = [i for i, x in enumerate(fields) if x == "No_Of_Valid_Recons"]
    
        for i,item in enumerate(proto):
            if item.startswith(fields[index]):
                if item.startswith("No_Of_Valid_Recons"):
                    rindex+=1
                    recon[rindex] = int(item.split(" ")[1])
                elif item.startswith("MlModeRecon_End"):
                    recon[rindex]-= 1
                    if recon[rindex] > 0:
                        if rindex == 0:
                            index = reconpos[0]
                        elif rindex == 1:
                            index = reconpos[1]
                        else: index = reconpos[2]
                index+=1
                fieldlist+=item + "\n"
#            if item.startswith("MapProtocolEntryUID:") and int(item[-1]) == 6:
#                print file + " " + item
    




        fieldlist = fieldlist[:-1]
        f = open(path2 + "fields56_" + file,'w')
        f.write(fieldlist)
        f.close()

    except:
        pass

